<?php

$ke_shi = array(
                "10" => array("name" => "内科",
                              "sub"  => array("1010" => array("name" => "心血管内科"),
                                              "1011" => array("name" => "神经内科"),
                                              "1012" => array("name" => "消化内科"),
                                              "1013" => array("name" => "内分泌科"),
                                              "1014" => array("name" => "免疫科"),
                                              "1015" => array("name" => "呼吸科"),
                                              "1016" => array("name" => "肾病内科"),
                                              "1017" => array("name" => "血液科"),
                                              "1018" => array("name" => "感染内科"),
                                              "1019" => array("name" => "过敏反应科"),
                                              "1020" => array("name" => "老年病科"),
                                              "1021" => array("name" => "疼痛诊疗科"),
                                              "1022" => array("name" => "高压氧科"),
                                              "1023" => array("name" => "普通科"),
                                              ),
                             ),
                "11" => array("name" => "外科",
                              "sub"  => array("1110" => array("name" => "神经外科"),
                                              "1111" => array("name" => "心血管外科"),
                                              "1112" => array("name" => "腹部外科"),
                                              "1113" => array("name" => "胸外科"),
                                              "1114" => array("name" => "整形科"),
                                              "1115" => array("name" => "乳腺外科"),
                                              "1116" => array("name" => "泌尿外科"),
                                              "1117" => array("name" => "肝胆外科"),
                                              "1118" => array("name" => "肛肠科"),
                                              "1119" => array("name" => "血管外科"),
                                              "1120" => array("name" => "功能神经外科"),
                                              "1121" => array("name" => "微创外科"),
                                              "1122" => array("name" => "普外科"),
                                             ),
                             ),
                "12" => array("name" => "妇产科",
                              "sub"  => array("1210" => array("name" => "妇科"),
                                              "1211" => array("name" => "产科"),
                                              "1212" => array("name" => "妇科内分泌"),
                                              "1213" => array("name" => "妇泌尿科"),
                                              "1214" => array("name" => "产前诊断科"),
                                              "1215" => array("name" => "遗传咨询科"),
                                              "1216" => array("name" => "计划生育科"),
                                              "1217" => array("name" => "妇产科"),
                                             ),
                             ),
                "13" => array("name" => "生殖中心",
                              "sub"  => array("1310" => array("name" => "生殖中心"),
                                             ),
                             ),
                "14" => array("name" => "儿科",
                              "sub"  => array("1410" => array("name" => "儿科"),
                                              "1411" => array("name" => "新生儿科"),
                                              "1412" => array("name" => "小儿呼吸科"),
                                              "1413" => array("name" => "小儿消化科"),
                                              "1414" => array("name" => "小儿营养保健科"),
                                              "1415" => array("name" => "小儿神经内科"),
                                              "1416" => array("name" => "小儿心内科"),
                                              "1417" => array("name" => "小儿肾内科"),
                                              "1418" => array("name" => "小儿血液科"),
                                              "1419" => array("name" => "小儿感染科"),
                                              "1420" => array("name" => "小儿精神科"),
                                              "1421" => array("name" => "小儿妇科"),
                                              "1422" => array("name" => "小儿外科"),
                                              "1423" => array("name" => "小儿心外科"),
                                              "1424" => array("name" => "小儿胸外科"),
                                              "1425" => array("name" => "小儿骨科"),
                                              "1426" => array("name" => "小儿泌尿科"),
                                              "1427" => array("name" => "小儿神经外科"),
                                              "1428" => array("name" => "小儿整形科"),
                                              "1429" => array("name" => "小儿康复科"),
                                              "1430" => array("name" => "小儿急诊科"),
                                             ),
                             ),
                "15" => array("name" => "骨科",
                              "sub"  => array("1510" => array("name" => "骨科"),
                                              "1511" => array("name" => "脊柱外科"),
                                              "1512" => array("name" => "手外科"),
                                              "1513" => array("name" => "创伤骨科"),
                                              "1514" => array("name" => "骨关节科"),
                                              "1515" => array("name" => "矫形骨科"),
                                              "1516" => array("name" => "骨肿瘤科"),
                                              "1517" => array("name" => "骨质疏松科"),
                                              "1518" => array("name" => "足踝外科"),
                                              "1519" => array("name" => "中西医结合正骨科"),
                                             ),
                             ),
                "16" => array("name" => "骨科",
                              "sub"  => array("1610" => array("name" => "眼肌"),
                                              "1611" => array("name" => "眼科"),
                                              "1612" => array("name" => "小儿眼科"),
                                              "1613" => array("name" => "眼底"),
                                              "1614" => array("name" => "角膜科"),
                                              "1615" => array("name" => "青光眼"),
                                              "1616" => array("name" => "白内障"),
                                              "1617" => array("name" => "眼外科"),
                                              "1618" => array("name" => "眼眶及肿瘤"),
                                              "1619" => array("name" => "屈光"),
                                              "1620" => array("name" => "眼整形"),
                                              "1621" => array("name" => "中医眼科"),
                                             ),
                             ),
                "17" => array("name" => "口腔科",
                              "sub"  => array("1710" => array("name" => "口腔科"),
                                              "1711" => array("name" => "颌面外科"),
                                              "1712" => array("name" => "正畸科"),
                                              "1713" => array("name" => "牙体牙髓科"),
                                              "1714" => array("name" => "牙周科"),
                                              "1715" => array("name" => "口腔黏膜科"),
                                              "1716" => array("name" => "儿童口腔科"),
                                              "1717" => array("name" => "口腔修复科"),
                                              "1718" => array("name" => "种植科"),
                                              "1719" => array("name" => "口腔预防科"),
                                              "1720" => array("name" => "综合科"),
                                              "1721" => array("name" => "口腔特诊科"),
                                              "1722" => array("name" => "老年口腔病科"),
                                              "1723" => array("name" => "口腔急诊科"),
                                             ),
                             ),
                "18" => array("name" => "耳鼻咽喉头颈科科",
                              "sub"  => array("1810" => array("name" => "耳科"),
                                              "1811" => array("name" => "鼻科"),
                                              "1812" => array("name" => "咽喉科"),
                                              "1813" => array("name" => "头颈外科"),
                                              "1814" => array("name" => "耳鼻喉科"),
                                             ),
                             ),
                "19" => array("name" => "肿瘤科",
                              "sub"  => array("1910" => array("name" => "肿瘤内科"),
                                              "1911" => array("name" => "肿瘤外科"),
                                              "1912" => array("name" => "肿瘤妇科"),
                                              "1913" => array("name" => "放疗科"),
                                              "1914" => array("name" => "骨肿瘤科"),
                                              "1915" => array("name" => "肿瘤康复科"),
                                              "1916" => array("name" => "肿瘤综合科"),
                                             ),
                             ),
                "20" => array("name" => "皮肤性病科",
                              "sub"  => array("2010" => array("name" => "皮肤科"),
                                              "2011" => array("name" => "性病科"),
                                             ),
                             ),
                "21" => array("name" => "男科",
                              "sub"  => array("2110" => array("name" => "男科"),
                                             ),
                             ),
                "22" => array("name" => "皮肤美容",
                              "sub"  => array("2210" => array("name" => "皮肤美容"),
                                             ),
                             ),
                "23" => array("name" => "烧伤科",
                              "sub"  => array("2310" => array("name" => "烧伤科"),
                                             ),
                             ),
                "24" => array("name" => "精神心理科",
                              "sub"  => array("2410" => array("name" => "精神科"),
                                              "2411" => array("name" => "心理咨询科"),
                                              "2412" => array("name" => "司法鉴定科"),
                                              "2413" => array("name" => "药物依赖科"),
                                             ),
                             ),
                "25" => array("name" => "中医科",
                              "sub"  => array("2510" => array("name" => "中医妇产科"),
                                              "2511" => array("name" => "中医儿科"),
                                              "2512" => array("name" => "中医骨科"),
                                              "2513" => array("name" => "中医皮肤科"),
                                              "2514" => array("name" => "中医内分泌"),
                                              "2515" => array("name" => "中医消化科"),
                                              "2516" => array("name" => "中医呼吸科"),
                                              "2517" => array("name" => "中医肾病内科"),
                                              "2518" => array("name" => "中医免疫科"),
                                              "2519" => array("name" => "中医心内科"),
                                              "2520" => array("name" => "中医神经内科"),
                                              "2521" => array("name" => "中医肿瘤科"),
                                              "2522" => array("name" => "中医血液科"),
                                              "2523" => array("name" => "中医感染内科"),
                                              "2524" => array("name" => "中医肝病科"),
                                              "2525" => array("name" => "中医五官科"),
                                              "2526" => array("name" => "中医男科"),
                                              "2527" => array("name" => "针灸科"),
                                              "2528" => array("name" => "中医按摩科"),
                                              "2529" => array("name" => "中医外科"),
                                              "2530" => array("name" => "中医乳腺外科"),
                                              "2531" => array("name" => "中医肝肠科"),
                                              "2532" => array("name" => "中医老年病科"),
                                              "2533" => array("name" => "中医理疗科"),
                                              "2534" => array("name" => "中医正骨科"),
                                              "2535" => array("name" => "中医科"),
                                             ),
                             ),
                "26" => array("name" => "中西医结合科",
                              "sub"  => array("2610" => array("name" => "中西医结合科"),
                                             ),
                             ),
                "27" => array("name" => "传染病科",
                              "sub"  => array("2710" => array("name" => "肝病科"),
                                              "2711" => array("name" => "传染科"),
                                              "2712" => array("name" => "艾滋病科"),
                                              "2713" => array("name" => "传染危重室"),
                                             ),
                             ),
                "28" => array("name" => "结核病科",
                              "sub"  => array("2810" => array("name" => "结核病科"),
                                             ),
                             ),
                "29" => array("name" => "介入医学科",
                              "sub"  => array("2910" => array("name" => "介入医学科"),
                                             ),
                             ),
                "30" => array("name" => "康复医学科",
                              "sub"  => array("3010" => array("name" => "康复科"),
                                              "3011" => array("name" => "理疗科"),
                                             ),
                             ),
                "31" => array("name" => "运动医学科",
                              "sub"  => array("3110" => array("name" => "运动医学科"),
                                             ),
                             ),
                "32" => array("name" => "麻醉医学科",
                              "sub"  => array("3210" => array("name" => "疼痛科"),
                                              "3011" => array("name" => "麻醉科"),
                                             ),
                             ),
                "33" => array("name" => "职业病科",
                              "sub"  => array("3310" => array("name" => "职业病科"),
                                             ),
                             ),
                "34" => array("name" => "地方病科",
                              "sub"  => array("3410" => array("name" => "地方病科"),
                                             ),
                             ),
                "35" => array("name" => "营养科",
                              "sub"  => array("3510" => array("name" => "营养科"),
                                             ),
                             ),
                "36" => array("name" => "医学影像科",
                              "sub"  => array("3610" => array("name" => "医学影像科"),
                                             ),
                             ),
                "37" => array("name" => "病理科",
                              "sub"  => array("3710" => array("name" => "病理科"),
                                             ),
                             ),
                "38" => array("name" => "其他科室",
                              "sub"  => array("3810" => array("name" => "急诊科"),
                                              "3811" => array("name" => "预防保健科"),
                                              "3812" => array("name" => "药剂科"),
                                              "3813" => array("name" => "体检科"),
                                              "3814" => array("name" => "血透中心"),
                                              "3815" => array("name" => "碎石中心"),
                                              "3816" => array("name" => "ICU"),
                                              "3817" => array("name" => "护理咨询"),
                                             ),
                             ),
                );

printf("%s\n", json_encode($ke_shi));

