<?php

$ke_shi = array(
                array("name" => "内科",
                      "sub"  => array(array("id" => 1010, "name" => "心血管内科"),
                                      array("id" => 1011, "name" => "神经内科"),
                                      array("id" => 1012, "name" => "消化内科"),
                                      array("id" => 1013, "name" => "内分泌科"),
                                      array("id" => 1014, "name" => "免疫科"),
                                      array("id" => 1015, "name" => "呼吸科"),
                                      array("id" => 1016, "name" => "肾病内科"),
                                      array("id" => 1017, "name" => "血液科"),
                                      array("id" => 1018, "name" => "感染内科"),
                                      array("id" => 1019, "name" => "过敏反应科"),
                                      array("id" => 1020, "name" => "老年病科"),
                                      array("id" => 1021, "name" => "疼痛诊疗科"),
                                      array("id" => 1022, "name" => "高压氧科"),
                                      array("id" => 1023, "name" => "普通科"),
                                      ),
                     ),
                array("name" => "外科",
                      "sub"  => array(array("id" => 1110, "name" => "神经外科"),
                                      array("id" => 1111, "name" => "心血管外科"),
                                      array("id" => 1112, "name" => "腹部外科"),
                                      array("id" => 1113, "name" => "胸外科"),
                                      array("id" => 1114, "name" => "整形科"),
                                      array("id" => 1115, "name" => "乳腺外科"),
                                      array("id" => 1116, "name" => "泌尿外科"),
                                      array("id" => 1117, "name" => "肝胆外科"),
                                      array("id" => 1118, "name" => "肛肠科"),
                                      array("id" => 1119, "name" => "血管外科"),
                                      array("id" => 1120, "name" => "功能神经外科"),
                                      array("id" => 1121, "name" => "微创外科"),
                                      array("id" => 1122, "name" => "普外科"),
                                     ),
                     ),
                array("name" => "妇产科",
                      "sub"  => array(array("id" => 1210, "name" => "妇科"),
                                      array("id" => 1211, "name" => "产科"),
                                      array("id" => 1212, "name" => "妇科内分泌"),
                                      array("id" => 1213, "name" => "妇泌尿科"),
                                      array("id" => 1214, "name" => "产前诊断科"),
                                      array("id" => 1215, "name" => "遗传咨询科"),
                                      array("id" => 1216, "name" => "计划生育科"),
                                      array("id" => 1217, "name" => "妇产科"),
                                     ),
                     ),
                array("name" => "生殖中心",
                      "sub"  => array(array("id" => 1310, "name" => "生殖中心")),
                     ),
                array("name" => "儿科",
                      "sub"  => array(array("id" => 1410, "name" => "儿科"),
                                      array("id" => 1411, "name" => "新生儿科"),
                                      array("id" => 1412, "name" => "小儿呼吸科"),
                                      array("id" => 1413, "name" => "小儿消化科"),
                                      array("id" => 1414, "name" => "小儿营养保健科"),
                                      array("id" => 1415, "name" => "小儿神经内科"),
                                      array("id" => 1416, "name" => "小儿心内科"),
                                      array("id" => 1417, "name" => "小儿肾内科"),
                                      array("id" => 1418, "name" => "小儿血液科"),
                                      array("id" => 1419, "name" => "小儿感染科"),
                                      array("id" => 1420, "name" => "小儿精神科"),
                                      array("id" => 1421, "name" => "小儿妇科"),
                                      array("id" => 1422, "name" => "小儿外科"),
                                      array("id" => 1423, "name" => "小儿心外科"),
                                      array("id" => 1424, "name" => "小儿胸外科"),
                                      array("id" => 1425, "name" => "小儿骨科"),
                                      array("id" => 1426, "name" => "小儿泌尿科"),
                                      array("id" => 1427, "name" => "小儿神经外科"),
                                      array("id" => 1428, "name" => "小儿整形科"),
                                      array("id" => 1429, "name" => "小儿康复科"),
                                      array("id" => 1430, "name" => "小儿急诊科"),
                                     ),
                     ),
                array("name" => "骨科",
                      "sub"  => array(array("id" => 1510, "name" => "骨科"),
                                      array("id" => 1511, "name" => "脊柱外科"),
                                      array("id" => 1512, "name" => "手外科"),
                                      array("id" => 1513, "name" => "创伤骨科"),
                                      array("id" => 1514, "name" => "骨关节科"),
                                      array("id" => 1515, "name" => "矫形骨科"),
                                      array("id" => 1516, "name" => "骨肿瘤科"),
                                      array("id" => 1517, "name" => "骨质疏松科"),
                                      array("id" => 1518, "name" => "足踝外科"),
                                      array("id" => 1519, "name" => "中西医结合正骨科"),
                                     ),
                     ),
                array("name" => "眼科",
                      "sub"  => array(array("id" => 1610, "name" => "眼肌"),
                                      array("id" => 1611, "name" => "眼科"),
                                      array("id" => 1612, "name" => "小儿眼科"),
                                      array("id" => 1613, "name" => "眼底"),
                                      array("id" => 1614, "name" => "角膜科"),
                                      array("id" => 1615, "name" => "青光眼"),
                                      array("id" => 1616, "name" => "白内障"),
                                      array("id" => 1617, "name" => "眼外科"),
                                      array("id" => 1618, "name" => "眼眶及肿瘤"),
                                      array("id" => 1619, "name" => "屈光"),
                                      array("id" => 1620, "name" => "眼整形"),
                                      array("id" => 1621, "name" => "中医眼科"),
                                     ),
                     ),
                array("name" => "口腔科",
                      "sub"  => array(array("id" => 1710, "name" => "口腔科"),
                                      array("id" => 1711, "name" => "颌面外科"),
                                      array("id" => 1712, "name" => "正畸科"),
                                      array("id" => 1713, "name" => "牙体牙髓科"),
                                      array("id" => 1714, "name" => "牙周科"),
                                      array("id" => 1715, "name" => "口腔黏膜科"),
                                      array("id" => 1716, "name" => "儿童口腔科"),
                                      array("id" => 1717, "name" => "口腔修复科"),
                                      array("id" => 1718, "name" => "种植科"),
                                      array("id" => 1719, "name" => "口腔预防科"),
                                      array("id" => 1720, "name" => "综合科"),
                                      array("id" => 1721, "name" => "口腔特诊科"),
                                      array("id" => 1722, "name" => "老年口腔病科"),
                                      array("id" => 1723, "name" => "口腔急诊科"),
                                     ),
                     ),
                array("name" => "耳鼻咽喉头颈科科",
                      "sub"  => array(array("id" => 1810, "name" => "耳科"),
                                      array("id" => 1811, "name" => "鼻科"),
                                      array("id" => 1812, "name" => "咽喉科"),
                                      array("id" => 1813, "name" => "头颈外科"),
                                      array("id" => 1814, "name" => "耳鼻喉科"),
                                     ),
                     ),
                array("name" => "肿瘤科",
                      "sub"  => array(array("id" => 1910, "name" => "肿瘤内科"),
                                      array("id" => 1911, "name" => "肿瘤外科"),
                                      array("id" => 1912, "name" => "肿瘤妇科"),
                                      array("id" => 1913, "name" => "放疗科"),
                                      array("id" => 1914, "name" => "骨肿瘤科"),
                                      array("id" => 1915, "name" => "肿瘤康复科"),
                                      array("id" => 1916, "name" => "肿瘤综合科"),
                                     ),
                     ),
                array("name" => "皮肤性病科",
                      "sub"  => array(array("id" => 2010, "name" => "皮肤科"),
                                      array("id" => 2011, "name" => "性病科"),
                                     ),
                     ),
                array("name" => "男科",
                      "sub"  => array(array("id" => 2110, "name" => "男科")),
                     ),
                array("name" => "皮肤美容",
                      "sub"  => array(array("id" => 2210, "name" => "皮肤美容")),
                     ),
                array("name" => "烧伤科",
                      "sub"  => array(array("id" => 2310, "name" => "烧伤科")),
                     ),
                array("name" => "精神心理科",
                      "sub"  => array(array("id" => 2410, "name" => "精神科"),
                                      array("id" => 2411, "name" => "心理咨询科"),
                                      array("id" => 2412, "name" => "司法鉴定科"),
                                      array("id" => 2413, "name" => "药物依赖科"),
                                     ),
                     ),
                array("name" => "中医科",
                      "sub"  => array(array("id" => 2510, "name" => "中医妇产科"),
                                      array("id" => 2511, "name" => "中医儿科"),
                                      array("id" => 2512, "name" => "中医骨科"),
                                      array("id" => 2513, "name" => "中医皮肤科"),
                                      array("id" => 2514, "name" => "中医内分泌"),
                                      array("id" => 2515, "name" => "中医消化科"),
                                      array("id" => 2516, "name" => "中医呼吸科"),
                                      array("id" => 2517, "name" => "中医肾病内科"),
                                      array("id" => 2518, "name" => "中医免疫科"),
                                      array("id" => 2519, "name" => "中医心内科"),
                                      array("id" => 2520, "name" => "中医神经内科"),
                                      array("id" => 2521, "name" => "中医肿瘤科"),
                                      array("id" => 2522, "name" => "中医血液科"),
                                      array("id" => 2523, "name" => "中医感染内科"),
                                      array("id" => 2524, "name" => "中医肝病科"),
                                      array("id" => 2525, "name" => "中医五官科"),
                                      array("id" => 2526, "name" => "中医男科"),
                                      array("id" => 2527, "name" => "针灸科"),
                                      array("id" => 2528, "name" => "中医按摩科"),
                                      array("id" => 2529, "name" => "中医外科"),
                                      array("id" => 2530, "name" => "中医乳腺外科"),
                                      array("id" => 2531, "name" => "中医肝肠科"),
                                      array("id" => 2532, "name" => "中医老年病科"),
                                      array("id" => 2533, "name" => "中医理疗科"),
                                      array("id" => 2534, "name" => "中医正骨科"),
                                      array("id" => 2535, "name" => "中医科"),
                                     ),
                     ),
                array("name" => "中西医结合科",
                      "sub"  => array(array("id" => 2610, "name" => "中西医结合科")),
                     ),
                array("name" => "传染病科",
                      "sub"  => array(array("id" => 2710, "name" => "肝病科"),
                                      array("id" => 2711, "name" => "传染科"),
                                      array("id" => 2712, "name" => "艾滋病科"),
                                      array("id" => 2713, "name" => "传染危重室"),
                                     ),
                     ),
                array("name" => "结核病科",
                      "sub"  => array(array("id" => 2810, "name" => "结核病科")),
                     ),
                array("name" => "介入医学科",
                      "sub"  => array(array("id" => 2910, "name" => "介入医学科")),
                     ),
                array("name" => "康复医学科",
                      "sub"  => array(array("id" => 3010, "name" => "康复科"),
                                      array("id" => 3011, "name" => "理疗科"),
                                     ),
                     ),
                array("name" => "运动医学科",
                      "sub"  => array(array("id" => 3110, "name" => "运动医学科")),
                     ),
                array("name" => "麻醉医学科",
                      "sub"  => array(array("id" => 3210, "name" => "疼痛科"),
                                      array("id" => 3011, "name" => "麻醉科"),
                                     ),
                     ),
                array("name" => "职业病科",
                      "sub"  => array(array("id" => 3310, "name" => "职业病科")),
                     ),
                array("name" => "地方病科",
                      "sub"  => array(array("id" => 3410, "name" => "地方病科")),
                     ),
                array("name" => "营养科",
                      "sub"  => array(array("id" => 3510, "name" => "营养科")),
                     ),
                array("name" => "医学影像科",
                      "sub"  => array(array("id" => 3610, "name" => "医学影像科")),
                     ),
                array("name" => "病理科",
                      "sub"  => array(array("id" => 3710, "name" => "病理科")),
                     ),
                array("name" => "其他科室",
                      "sub"  => array(array("id" => 3810, "name" => "急诊科"),
                                      array("id" => 3811, "name" => "预防保健科"),
                                      array("id" => 3812, "name" => "药剂科"),
                                      array("id" => 3813, "name" => "体检科"),
                                      array("id" => 3814, "name" => "血透中心"),
                                      array("id" => 3815, "name" => "碎石中心"),
                                      array("id" => 3816, "name" => "ICU"),
                                      array("id" => 3817, "name" => "护理咨询"),
                                     ),
                     ),
                );

printf("%s\n", json_encode($ke_shi));

